function figure_handle = ts_plot_calibration (calibration, fontSize)
  if (nargin < 1 || nargin > 2)
    print_usage ();
  endif
  if (nargin < 2)
    fontSize = 12;
  endif
  figure_handle = figure ("name", "Calibracao angular MT6701", ...
                          "numbertitle", "off", "units", "normalized", ...
                          "position", [0.12, 0.12, 0.76, 0.72]);
  subplot (2, 1, 1);
  plot (calibration.lut_angle_deg, calibration.correction_deg, ...
        "linewidth", 1.3);
  grid on;
  ylabel ("correcao [deg]");
  title (sprintf ("LUT de %d pontos - CRC %08X", ...
                  calibration.bin_count, calibration.payload_crc32));

  subplot (2, 1, 2);
  plot (calibration.phase_deg, calibration.validation_raw_error_deg, ...
        "linewidth", 1.1, calibration.phase_deg, ...
        calibration.validation_corrected_error_deg, "linewidth", 1.2);
  grid on;
  xlabel ("angulo bruto [deg]");
  ylabel ("erro de fase [deg]");
  legend ("antes", "depois", "location", "northeast");
  title (sprintf (["Validacao: fase %.4f -> %.4f deg (%.1f%%); ", ...
                  "velocidade %.2f -> %.2f rpm (%.1f%%)"], ...
                  calibration.raw_rms_deg, ...
                  calibration.corrected_rms_deg, ...
                  calibration.reduction_percent, ...
                  calibration.raw_speed_rms_rpm, ...
                  calibration.corrected_speed_rms_rpm, ...
                  calibration.speed_reduction_percent));
  set (findall (figure_handle, "type", "axes"), "fontsize", fontSize);
  set (findall (figure_handle, "type", "text"), "fontsize", fontSize);
endfunction
